
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/raiserbuddy
    username: admin
    password: good
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

